<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ResumeEnhancer.Tests.Unit</AssemblyName>
    <RootNamespace>ResumeEnhancer.Tests.Unit</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Update="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NetArchTest.Rules" Version="1.3.2" />
    <ProjectReference Include="..\..\application\Core\DomainLibrary\ResumeEnhancer.Core.DomainLibrary.csproj" />
    <ProjectReference Include="..\..\application\Core\WebLibrary\ResumeEnhancer.Core.WebLibrary.csproj" />
    <ProjectReference Include="..\..\application\Infrastructure\Caching\ResumeEnhancer.Infrastructure.Caching.csproj" />
    <ProjectReference Include="..\..\application\Infrastructure\Migration\ResumeEnhancer.Infrastructure.Migration.csproj" />
    <ProjectReference Include="..\..\application\Infrastructure\Persistence\ResumeEnhancer.Infrastructure.Persistence.csproj" />
    <ProjectReference Include="..\..\application\Modules\ResumeModule\ResumeModuleAM\ResumeEnhancer.ResumeModule.AM.csproj" />
    <ProjectReference Include="..\..\application\Modules\ResumeModule\ResumeModuleDM\ResumeEnhancer.ResumeModule.DM.csproj" />
    <ProjectReference Include="..\..\application\Modules\ResumeModule\ResumeModulePL\ResumeEnhancer.ResumeModule.PL.csproj" />
    <ProjectReference Include="..\..\application\Modules\ResumeModule\ResumeModelSL\ResumeEnhancer.ResumeModule.SL.csproj" />
    <ProjectReference Include="..\..\application\Modules\ResumeModule\ResumeModuleWeb\ResumeEnhancer.ResumeModule.Web.csproj" />
    <ProjectReference Include="..\..\application\WebSolution\ModulesComposition\ResumeEnhancer.WebSolution.ModulesComposition.csproj" />
  </ItemGroup>
</Project>

