<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ResumeEnhancer.IntegrationTests</AssemblyName>
    <RootNamespace>ResumeEnhancer.IntegrationTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" Version="35.6.3" />
    <PackageReference Include="morelinq" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\application\Core\DomainLibrary\DomainLibrary.csproj" />
    <ProjectReference Include="..\..\application\Core\WebLibrary\WebLibrary.csproj" />
    <ProjectReference Include="..\..\application\Infrastructure\Caching\Caching.csproj" />
    <ProjectReference Include="..\..\application\Infrastructure\Persistence\Persistence.csproj" />
    <ProjectReference Include="..\..\application\Modules\ResumeModule\ResumeModuleAM\ResumeModuleAM.csproj" />
    <ProjectReference Include="..\..\application\Modules\ResumeModule\ResumeModuleDM\ResumeModuleDM.csproj" />
    <ProjectReference Include="..\..\application\Modules\ResumeModule\ResumeModulePL\ResumeModulePL.csproj" />
    <ProjectReference Include="..\..\application\Modules\ResumeModule\ResumeModelSL\ResumeModuleSL.csproj" />
    <ProjectReference Include="..\..\application\Modules\ResumeModule\ResumeModuleWeb\ResumeModuleWeb.csproj" />
    <ProjectReference Include="..\..\application\WebSolution\ModulesComposition\ModulesComposition.csproj" />
    <ProjectReference Include="..\..\application\WebSolution\WebSolution.Server\WebSolution.Server.csproj" />
    <ProjectReference Include="..\TestUtilities\IntegrationSupport\IntegrationSupport.csproj" />
  </ItemGroup>
</Project>
