<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\CommonLibrary\CommonLibrary.csproj" />
    <ProjectReference Include="..\ResumeModuleAM\ResumeModuleAM.csproj" />
    <ProjectReference Include="..\ResumeModuleDM\ResumeModuleDM.csproj" />
    <ProjectReference Include="..\ResumeModulePL\ResumeModulePL.csproj" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Contracts\" />
    <Folder Include="Implementation\" />
  </ItemGroup>

</Project>
