<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Infrastructure\Caching\Caching.csproj" />
    <ProjectReference Include="..\..\..\Infrastructure\Persistence\Persistence.csproj" />
    <ProjectReference Include="..\ResumeModuleDM\ResumeModuleDM.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Contracts\" />
    <Folder Include="Implementation\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.9" />
  </ItemGroup>

</Project>
