<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\DomainLibrary\ResumeEnhancer.Core.DomainLibrary.csproj" />
    <ProjectReference Include="..\..\ProfilingModule\ProfilingModuleDM\ResumeEnhancer.ProfilingModule.DM.csproj" />
    <ProjectReference Include="..\..\TemplateModule\TemplateModuleDM\ResumeEnhancer.TemplateModule.DM.csproj" />
  </ItemGroup>

</Project>

