<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mediator.Abstractions" Version="3.0.2" />
    <PackageReference Include="Mediator.SourceGenerator" Version="3.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Modules\BillingModule\BillingModulePL\ResumeEnhancer.BillingModule.PL.csproj" />
    <ProjectReference Include="..\..\Modules\BillingModule\BillingModuleWeb\ResumeEnhancer.BillingModule.Web.csproj" />
    <ProjectReference Include="..\..\Modules\ProfilingModule\ProfilingModulePL\ResumeEnhancer.ProfilingModule.PL.csproj" />
    <ProjectReference Include="..\..\Modules\ProfilingModule\ProfilingModuleWeb\ResumeEnhancer.ProfilingModule.Web.csproj" />
    <ProjectReference Include="..\..\Modules\ResumeModule\ResumeModulePL\ResumeEnhancer.ResumeModule.PL.csproj" />
    <ProjectReference Include="..\..\Modules\ResumeModule\ResumeModuleWeb\ResumeEnhancer.ResumeModule.Web.csproj" />
    <ProjectReference Include="..\..\Modules\TemplateModule\TemplateModulePL\ResumeEnhancer.TemplateModule.PL.csproj" />
    <ProjectReference Include="..\..\Modules\TemplateModule\TemplateModuleWeb\ResumeEnhancer.TemplateModule.Web.csproj" />
  </ItemGroup>

</Project>

